<?php


//DO NOT ALTER, THIS FILE IS GENERATED BY CONTENTFUL WP


include_once 'cwp_56f9c2cc175d4.php';
include_once 'cwp_56f9c2cc1794c.php';
include_once 'cwp_56f9c2cc17bfd.php';
include_once 'cwp_56f9c2cc17e57.php';
include_once 'cwp_56f9c2cc181ad.php';
include_once 'cwp_56f9c2cc183ad.php';
include_once 'cwp_56f9c2cc185e2.php';