<?php

	        //Generated by Contentful WP
	        //Author: Tanios
	        //Developer: Guillaume Laliberté

	        add_action( 'init', 'contentful_register_cpt_cwp_56f9c2cc1794c' );
	        function contentful_register_cpt_cwp_56f9c2cc1794c() {
		        $labels = array(
			        "name" => "Beacons",
			        "singular_name" => "Beacons",
		        );

		        $args = array(
			        "labels" => $labels,
			        "description" => "",
			        "public" => true,
			        "show_ui" => true,
			        "show_in_rest" => false,
			        "has_archive" => true,
			        "show_in_menu" => true,
			        "exclude_from_search" => false,
			        "capability_type" => "post",
			        "map_meta_cap" => true,
			        "hierarchical" => false,
			        "rewrite" => array( "slug" => "beacons", "with_front" => true ),
			        "query_var" => true,
			        "supports" => false,
		        );
		        register_post_type( "cwp_56f9c2cc1794c", $args );
	        }

            if(function_exists("register_field_group"))
            {
                register_field_group(array (
                    'id' => 'acf_contentful_beacons',
                    'title' => 'Beacons',
                    'fields' => array (

                        
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc17a19',
                                'label' => 'Name',
                                'name' => 'name',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '256',
			                    'required' => ''
                            ),
                            
                            
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc17a5b',
                                'label' => 'UDID',
                                'name' => 'udid',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '256',
			                    'required' => ''
                            ),
                            
                            
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc17a9a',
                                'label' => 'Major',
                                'name' => 'major',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '256',
			                    'required' => ''
                            ),
                            
                            
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc17ad8',
                                'label' => 'Minor',
                                'name' => 'minor',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '256',
			                    'required' => ''
                            ),
                            
                            
                        
					        
                                                            						        array (
							        'key' => 'field_56f9c2cc17b18',
							        'label' => 'Room',
							        'name' => 'room',
							        'type' => 'relationship',
							        'return_format' => 'id',
							        'post_type' => array (
							            0 => 'all',
							        ),
							        'taxonomy' => array (
							            0 => 'all',
							        ),
							        'filters' => array (
							            0 => 'search',
							        ),
							        'result_elements' => array (
							            0 => 'post_type',
							            1 => 'post_title',
							        ),
							        'max' => '',
				                    'required' => ''
						        ),
				                                            
                            
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc17b57',
                                'label' => 'UUID',
                                'name' => 'uuid',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '256',
			                    'required' => ''
                            ),
                            
                            
                                            ),
                    'location' => array (
                        array (
                            array (
                                'param' => 'post_type',
                                'operator' => '==',
                                'value' => 'cwp_56f9c2cc1794c',
                                'order_no' => 0,
                                'group_no' => 0,
                            ),
                        ),
                    ),
                    'options' => array (
                        'position' => 'acf_after_title',
                        'layout' => 'default',
                        'hide_on_screen' => array (
                        ),
                    ),
                    'menu_order' => 0,
                ));
            }

            //filters for field type
            add_filter( 'contentful_field_type_cwp_56f9c2cc1794c', function( $field ) {

                //defaulted to symbol
                $type = 'Symbol';

                //getting field type
                switch( $field )
                {
                                        case 'name':
                        $type = 'Symbol';
                    break;
                                        case 'udid':
                        $type = 'Symbol';
                    break;
                                        case 'major':
                        $type = 'Symbol';
                    break;
                                        case 'minor':
                        $type = 'Symbol';
                    break;
                                        case 'room':
                        $type = 'Entry';
                    break;
                                        case 'uuid':
                        $type = 'Symbol';
                    break;
                                    }

                //returning type
                return $type;

            } );

            