<?php

	        //Generated by Contentful WP
	        //Author: Tanios
	        //Developer: Guillaume Laliberté

	        add_action( 'init', 'contentful_register_cpt_cwp_56f9c2cc185e2' );
	        function contentful_register_cpt_cwp_56f9c2cc185e2() {
		        $labels = array(
			        "name" => "commentary",
			        "singular_name" => "commentary",
		        );

		        $args = array(
			        "labels" => $labels,
			        "description" => "",
			        "public" => true,
			        "show_ui" => true,
			        "show_in_rest" => false,
			        "has_archive" => true,
			        "show_in_menu" => true,
			        "exclude_from_search" => false,
			        "capability_type" => "post",
			        "map_meta_cap" => true,
			        "hierarchical" => false,
			        "rewrite" => array( "slug" => "commentary", "with_front" => true ),
			        "query_var" => true,
			        "supports" => false,
		        );
		        register_post_type( "cwp_56f9c2cc185e2", $args );
	        }

            if(function_exists("register_field_group"))
            {
                register_field_group(array (
                    'id' => 'acf_contentful_commentary',
                    'title' => 'commentary',
                    'fields' => array (

                        
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc186be',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '256',
			                    'required' => ''
                            ),
                            
                            
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc18701',
                                'label' => 'Short Description',
                                'name' => 'shortDescription',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '256',
			                    'required' => ''
                            ),
                            
                            
                        
					        
                                                                                            array (
                                    'key' => 'field_56f9c2cc18741',
                                    'label' => 'Banner',
                                    'name' => 'banner',
                                    'type' => 'file',
                                    'column_width' => '',
                                    'save_format' => 'id',
                                    'library' => 'all',
                                    'required' => ''
                                ),
                                                            
                            
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc18782',
                                'label' => 'Content',
                                'name' => 'content',
                                'type' => 'wysiwyg',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
			                    'required' => ''
                            ),
                            
                            
                        
					        
                                                            						        array (
							        'key' => 'field_56f9c2cc187c3',
							        'label' => 'Room',
							        'name' => 'room',
							        'type' => 'relationship',
							        'return_format' => 'id',
							        'post_type' => array (
							            0 => 'all',
							        ),
							        'taxonomy' => array (
							            0 => 'all',
							        ),
							        'filters' => array (
							            0 => 'search',
							        ),
							        'result_elements' => array (
							            0 => 'post_type',
							            1 => 'post_title',
							        ),
							        'max' => '',
				                    'required' => ''
						        ),
				                                            
                            
                        
					        
                                                            						        array (
							        'key' => 'field_56f9c2cc18803',
							        'label' => 'Author',
							        'name' => 'author',
							        'type' => 'relationship',
							        'return_format' => 'id',
							        'post_type' => array (
							            0 => 'all',
							        ),
							        'taxonomy' => array (
							            0 => 'all',
							        ),
							        'filters' => array (
							            0 => 'search',
							        ),
							        'result_elements' => array (
							            0 => 'post_type',
							            1 => 'post_title',
							        ),
							        'max' => '',
				                    'required' => ''
						        ),
				                                            
                            
                                            ),
                    'location' => array (
                        array (
                            array (
                                'param' => 'post_type',
                                'operator' => '==',
                                'value' => 'cwp_56f9c2cc185e2',
                                'order_no' => 0,
                                'group_no' => 0,
                            ),
                        ),
                    ),
                    'options' => array (
                        'position' => 'acf_after_title',
                        'layout' => 'default',
                        'hide_on_screen' => array (
                        ),
                    ),
                    'menu_order' => 0,
                ));
            }

            //filters for field type
            add_filter( 'contentful_field_type_cwp_56f9c2cc185e2', function( $field ) {

                //defaulted to symbol
                $type = 'Symbol';

                //getting field type
                switch( $field )
                {
                                        case 'title':
                        $type = 'Symbol';
                    break;
                                        case 'shortDescription':
                        $type = 'Symbol';
                    break;
                                        case 'banner':
                        $type = 'Asset';
                    break;
                                        case 'content':
                        $type = 'Text';
                    break;
                                        case 'room':
                        $type = 'Entry';
                    break;
                                        case 'author':
                        $type = 'Entry';
                    break;
                                    }

                //returning type
                return $type;

            } );

            