<?php

	        //Generated by Contentful WP
	        //Author: Tanios
	        //Developer: Guillaume Laliberté

	        add_action( 'init', 'contentful_register_cpt_cwp_56f9c2cc183ad' );
	        function contentful_register_cpt_cwp_56f9c2cc183ad() {
		        $labels = array(
			        "name" => "Slides",
			        "singular_name" => "Slides",
		        );

		        $args = array(
			        "labels" => $labels,
			        "description" => "The intro slides",
			        "public" => true,
			        "show_ui" => true,
			        "show_in_rest" => false,
			        "has_archive" => true,
			        "show_in_menu" => true,
			        "exclude_from_search" => false,
			        "capability_type" => "post",
			        "map_meta_cap" => true,
			        "hierarchical" => false,
			        "rewrite" => array( "slug" => "slides", "with_front" => true ),
			        "query_var" => true,
			        "supports" => false,
		        );
		        register_post_type( "cwp_56f9c2cc183ad", $args );
	        }

            if(function_exists("register_field_group"))
            {
                register_field_group(array (
                    'id' => 'acf_contentful_slides',
                    'title' => 'Slides',
                    'fields' => array (

                        
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc1847d',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '256',
			                    'required' => ''
                            ),
                            
                            
                        
					        
                                                                                            array (
                                    'key' => 'field_56f9c2cc184c1',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'file',
                                    'column_width' => '',
                                    'save_format' => 'id',
                                    'library' => 'all',
                                    'required' => ''
                                ),
                                                            
                            
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc18502',
                                'label' => 'Order',
                                'name' => 'order',
                                'type' => 'number',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
			                    'required' => ''
                            ),
                            
                            
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc18542',
                                'label' => 't_order',
                                'name' => 'tOrder',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '256',
			                    'required' => ''
                            ),
                            
                            
                                            ),
                    'location' => array (
                        array (
                            array (
                                'param' => 'post_type',
                                'operator' => '==',
                                'value' => 'cwp_56f9c2cc183ad',
                                'order_no' => 0,
                                'group_no' => 0,
                            ),
                        ),
                    ),
                    'options' => array (
                        'position' => 'acf_after_title',
                        'layout' => 'default',
                        'hide_on_screen' => array (
                        ),
                    ),
                    'menu_order' => 0,
                ));
            }

            //filters for field type
            add_filter( 'contentful_field_type_cwp_56f9c2cc183ad', function( $field ) {

                //defaulted to symbol
                $type = 'Symbol';

                //getting field type
                switch( $field )
                {
                                        case 'title':
                        $type = 'Symbol';
                    break;
                                        case 'image':
                        $type = 'Asset';
                    break;
                                        case 'order':
                        $type = 'Integer';
                    break;
                                        case 'tOrder':
                        $type = 'Symbol';
                    break;
                                    }

                //returning type
                return $type;

            } );

            