<?php

	        //Generated by Contentful WP
	        //Author: Tanios
	        //Developer: Guillaume Laliberté

	        add_action( 'init', 'contentful_register_cpt_cwp_56f9c2cc181ad' );
	        function contentful_register_cpt_cwp_56f9c2cc181ad() {
		        $labels = array(
			        "name" => "Author",
			        "singular_name" => "Author",
		        );

		        $args = array(
			        "labels" => $labels,
			        "description" => "",
			        "public" => true,
			        "show_ui" => true,
			        "show_in_rest" => false,
			        "has_archive" => true,
			        "show_in_menu" => true,
			        "exclude_from_search" => false,
			        "capability_type" => "post",
			        "map_meta_cap" => true,
			        "hierarchical" => false,
			        "rewrite" => array( "slug" => "author", "with_front" => true ),
			        "query_var" => true,
			        "supports" => false,
		        );
		        register_post_type( "cwp_56f9c2cc181ad", $args );
	        }

            if(function_exists("register_field_group"))
            {
                register_field_group(array (
                    'id' => 'acf_contentful_author',
                    'title' => 'Author',
                    'fields' => array (

                        
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc1827e',
                                'label' => 'Name',
                                'name' => 'name',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '256',
			                    'required' => ''
                            ),
                            
                            
                        
					        
                                                                                            array (
                                    'key' => 'field_56f9c2cc182c3',
                                    'label' => 'Profile Picture',
                                    'name' => 'profilePicture',
                                    'type' => 'file',
                                    'column_width' => '',
                                    'save_format' => 'id',
                                    'library' => 'all',
                                    'required' => ''
                                ),
                                                            
                            
                        
					        
                                                        array (
                                'key' => 'field_56f9c2cc18303',
                                'label' => 'Organization',
                                'name' => 'organization',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '256',
			                    'required' => ''
                            ),
                            
                            
                                            ),
                    'location' => array (
                        array (
                            array (
                                'param' => 'post_type',
                                'operator' => '==',
                                'value' => 'cwp_56f9c2cc181ad',
                                'order_no' => 0,
                                'group_no' => 0,
                            ),
                        ),
                    ),
                    'options' => array (
                        'position' => 'acf_after_title',
                        'layout' => 'default',
                        'hide_on_screen' => array (
                        ),
                    ),
                    'menu_order' => 0,
                ));
            }

            //filters for field type
            add_filter( 'contentful_field_type_cwp_56f9c2cc181ad', function( $field ) {

                //defaulted to symbol
                $type = 'Symbol';

                //getting field type
                switch( $field )
                {
                                        case 'name':
                        $type = 'Symbol';
                    break;
                                        case 'profilePicture':
                        $type = 'Asset';
                    break;
                                        case 'organization':
                        $type = 'Symbol';
                    break;
                                    }

                //returning type
                return $type;

            } );

            